/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_brewchain_core_crypto_jni_IPPCrypto */

#ifndef _Included_org_brewchain_core_crypto_jni_IPPCrypto
#define _Included_org_brewchain_core_crypto_jni_IPPCrypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_brewchain_core_crypto_jni_IPPCrypto
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_brewchain_core_crypto_jni_IPPCrypto_init
  (JNIEnv *, jobject);

/*
 * Class:     org_brewchain_core_crypto_jni_IPPCrypto
 * Method:    genKeys
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_org_brewchain_core_crypto_jni_IPPCrypto_genKeys
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_brewchain_core_crypto_jni_IPPCrypto
 * Method:    signMessage
 * Signature: ([B[B[BLjava/lang/String;[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_brewchain_core_crypto_jni_IPPCrypto_signMessage
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jstring, jbyteArray, jbyteArray);

/*
 * Class:     org_brewchain_core_crypto_jni_IPPCrypto
 * Method:    verifyMessage
 * Signature: ([B[BLjava/lang/String;[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_brewchain_core_crypto_jni_IPPCrypto_verifyMessage
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jstring, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
